orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1

jobs:
  
  build-push-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t confiman/golang-hello-app:latest .
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker push confiman/golang-hello-app:latest

workflows:
  deployment:
    jobs:
	  - build-push-docker-image