orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1

jobs:
  
  build-push-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t confiman/golang-hello-app:latest .
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker push confiman/golang-hello-app:latest
  
  deploy-to-stage:
    machine: true
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: hepsiburada
          perform-login: true
          resource-group: Default
      - run:
          command: | 
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run: helm upgrade --install golang-hello-app golang-hello/ --namespace=dev -f golang-hello/values.yaml --set-string image.tag="latest" --set ingress.hosts[0].host=yavuzyildirim.westus.cloudapp.azure.com --set ingress.hosts[0].paths[0]="/" --set ingress.tls[0].secretName=tls-secret --set ingress.tls[0].hosts[0]="yavuzyildirim.westus.cloudapp.azure.com"
    

workflows:
  deployment:
    jobs:
      - build-push-docker-image
      - deploy-to-stage:
          requires:
            - build-push-docker-image
